// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';
// LEGACY: Supabase client retained for hooks/services not yet migrated to Convex.
// Backend is now Convex — this client is only used by legacy code paths.
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL ?? '';
const supabaseKey = import.meta.env.VITE_SUPABASE_ANON_KEY ?? '';

type SupabaseClientType = SupabaseClient<Database>;

declare global {
  var __NAM_LEND_SUPABASE__: SupabaseClientType | undefined;
}

let supabaseClient: SupabaseClientType | undefined = globalThis.__NAM_LEND_SUPABASE__;

if (!supabaseClient) {
  supabaseClient = createClient<Database>(
    supabaseUrl || 'https://placeholder.supabase.co',
    supabaseKey || 'placeholder',
    {
      auth: {
        persistSession: true,
        autoRefreshToken: true,
        detectSessionInUrl: true,
        storage: window.localStorage,
        storageKey: 'namlend-auth',
      },
    }
  );
  globalThis.__NAM_LEND_SUPABASE__ = supabaseClient;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = supabaseClient!;
