// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { mockSupabase } from './mockClient';

// Prefer environment variables in production. Fallback to generated values for local/dev.
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Detect if we should use mock client for development
const useMockClient = !supabaseUrl || !supabaseKey || 
  supabaseUrl.includes('demo.supabase.co') || 
  supabaseKey === 'demo-anon-key';

// SECURITY: Fail fast in production if credentials are missing
const isProduction = import.meta.env.PROD || 
  import.meta.env.MODE === 'production' ||
  window?.location?.hostname?.includes('netlify.app') ||
  window?.location?.hostname?.includes('namlend');

if (isProduction && useMockClient) {
  console.error('🚨 CRITICAL: Supabase credentials missing in production environment!');
  throw new Error(
    'Supabase configuration error: VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY must be set in production. ' +
    'Please check your environment variables.'
  );
}

// Type for our Supabase client - use SupabaseClient type to get proper method signatures
// The mock client is structurally compatible at runtime, and we use type assertion to avoid union issues
type SupabaseClientType = SupabaseClient<Database>;

// Ensure a singleton across HMR reloads to avoid multiple GoTrueClient warnings
declare global {
  // eslint-disable-next-line no-var
  var __NAM_LEND_SUPABASE__: SupabaseClientType | undefined;
}

let supabaseClient: SupabaseClientType | undefined = globalThis.__NAM_LEND_SUPABASE__;

if (!supabaseClient) {
  if (useMockClient) {
    // Using mock client for development (no real Supabase credentials)
    // Type assertion needed as mock doesn't implement all SupabaseClient properties
    supabaseClient = mockSupabase as unknown as SupabaseClientType;
  } else {
    supabaseClient = createClient<Database>(supabaseUrl, supabaseKey, {
      auth: {
        persistSession: true,
        autoRefreshToken: true,
        detectSessionInUrl: true,
        storage: window.localStorage,
        storageKey: 'namlend-auth'
      },
    });
  }
  globalThis.__NAM_LEND_SUPABASE__ = supabaseClient;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = supabaseClient!;